#!/bin/bash
# Installation script for PT Analytics cron jobs

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get absolute path to project directory
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
CRON_SCRIPTS_DIR="$PROJECT_DIR/cron_scripts"
LOGS_DIR="$PROJECT_DIR/logs"

echo -e "${GREEN}PT Analytics - Cron Installation${NC}"
echo "=================================="
echo "Project directory: $PROJECT_DIR"
echo ""

# Step 1: Create logs directory
echo -e "${YELLOW}Step 1: Creating logs directory...${NC}"
mkdir -p "$LOGS_DIR"
echo "✓ Created $LOGS_DIR"
echo ""

# Step 2: Make scripts executable
echo -e "${YELLOW}Step 2: Making scripts executable...${NC}"
chmod +x "$CRON_SCRIPTS_DIR/run_ingestion.py"
chmod +x "$CRON_SCRIPTS_DIR/run_analysis.py"
echo "✓ Scripts are executable"
echo ""

# Step 3: Find Python path
echo -e "${YELLOW}Step 3: Detecting Python...${NC}"
PYTHON_PATH=$(which python3)
if [ -z "$PYTHON_PATH" ]; then
    echo -e "${RED}ERROR: python3 not found${NC}"
    exit 1
fi
echo "✓ Python found at: $PYTHON_PATH"
echo ""

# Step 4: Test scripts
echo -e "${YELLOW}Step 4: Testing scripts...${NC}"
echo "Testing ingestion script..."
cd "$PROJECT_DIR"
$PYTHON_PATH "$CRON_SCRIPTS_DIR/run_ingestion.py"
if [ $? -eq 0 ]; then
    echo "✓ Ingestion script works"
else
    echo -e "${RED}✗ Ingestion script failed${NC}"
    exit 1
fi

echo "Testing analysis script..."
$PYTHON_PATH "$CRON_SCRIPTS_DIR/run_analysis.py"
if [ $? -eq 0 ]; then
    echo "✓ Analysis script works"
else
    echo -e "${RED}✗ Analysis script failed${NC}"
    exit 1
fi
echo ""

# Step 5: Generate crontab
echo -e "${YELLOW}Step 5: Generating crontab...${NC}"
TEMP_CRON=$(mktemp)

cat > "$TEMP_CRON" << EOF
# PT Analytics Cron Jobs
# Generated by install_cron.sh on $(date)
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
PYTHON=$PYTHON_PATH
PROJECT_DIR=$PROJECT_DIR
LOGS_DIR=$LOGS_DIR

# INGESTION - Every 10 seconds (6 times per minute)
* * * * * for i in {0..5}; do \$PYTHON \$PROJECT_DIR/cron_scripts/run_ingestion.py >> \$LOGS_DIR/ingestion.log 2>&1 & sleep 10; done

# ANALYSIS - Every 10 minutes
*/10 * * * * \$PYTHON \$PROJECT_DIR/cron_scripts/run_analysis.py >> \$LOGS_DIR/analysis.log 2>&1

# LOG ROTATION - Daily at 2 AM
0 2 * * * find \$LOGS_DIR -name "*.log" -size +50M -exec truncate -s 0 {} \;
EOF

echo "✓ Crontab generated"
echo ""

# Step 6: Show current crontab
echo -e "${YELLOW}Step 6: Current crontab${NC}"
crontab -l 2>/dev/null || echo "(no crontab)"
echo ""

# Step 7: Install
echo -e "${YELLOW}Step 7: Install crontab?${NC}"
echo "This will replace your current crontab."
echo "Backup saved to: $LOGS_DIR/crontab.backup.$(date +%s)"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Backup current crontab
    crontab -l > "$LOGS_DIR/crontab.backup.$(date +%s)" 2>/dev/null || true
    
    # Install new crontab
    crontab "$TEMP_CRON"
    
    echo -e "${GREEN}✓ Crontab installed${NC}"
    echo ""
    echo "New crontab:"
    crontab -l
    echo ""
    echo -e "${GREEN}Installation complete!${NC}"
    echo ""
    echo "Monitor logs:"
    echo "  tail -f $LOGS_DIR/ingestion.log"
    echo "  tail -f $LOGS_DIR/analysis.log"
else
    echo -e "${YELLOW}Installation cancelled${NC}"
    echo "Generated crontab saved to: $TEMP_CRON"
fi

rm -f "$TEMP_CRON" 2>/dev/null || true
